### PR TITLE
Network Reachability

### LINKED ISSUE #103: Add network awareness/offline support
Currently if the network is slow to respond, the app sort of just craps out. We should add features to detect a poor network condition and display a banner that indicates the status and gives the user the option of retrying.

### PR DESCRIPTION
**Pull request by chickdan**
Had some code laying around and plugged it in to get network detection going and added the [NotificationBanner](https://github.com/Daltron/NotificationBanner) library for displaying a banner. Currently the only banner being displayed is when there is no network connection at all, but I plan on expanding the logic to display for various situations with corresponding messages.

This code is kind of old so I'm looking at using the [Reachability.swift](https://github.com/ashleymills/Reachability.swift) library which looks pretty similar but more refined.

Closes #103

### CODE REVIEW

**Comment by benhalpern** [comment]
This looks great. I'll take a look within the next day. @StriderHND wanna play around with this and offer some thoughts?

**Comment by StriderHND** [comment]
Sure I'll checkout this @benhalpern , and give my comments.

**Comment by chickdan** [comment]
In 8681c0c I added an error banner as a lazy var, this is to provide access the banner to dismiss it since `autoDismiss = false`. Along with that there are two new banners that will conditionally display if moving from no connection to being connected to either cellular or WiFi.

I'll be tackling the code climate issues soon.

**Comment by benhalpern** [comment]
Having finally given it a full inspection, this is a fabulous first pass.

This is an area we are going to want to keep improving on as a strength and this is an awesome start to iterate off. Amazing work @chickdan.

**Pull request merged**
