### PR TITLE
Feature/iPad support

### PR DESCRIPTION
**Pull request by StriderHND**
In this PR we add support to iPad devices as requested in the issue #100 

Updating the project and doing some small refectory how the `URL` are loaded I created an extension to `WKWebView` creating a function called `load` in this version of load we send a string of the URL we need to load, creates a `URL` object and a `URLRequest` with that we assure that we do optional unwrapping of the string we need to load and update the `wkwebview`. with that now we can load URL string in the following way

`webView.load("url_string-to_load")`and not do all the optional boilerplate code to unwrap or request.

Storyboard Updates.

- Added a UIToolbar to the ViewController storyboard
- Updated the forward and back buttons from UIButton to UIBarButtons for the UIToolbar
- Corrected constrains warnings on storyboards

If there is any questions please let me know 

Erick

### CODE REVIEW

**Comment by chickdan** [comment]
Great update, this looks so much better on iPad! 

For future reference, and this applies to any project, it's best to keep unrelated changes as separate PRs just in case something doesn't work, a maintainer doesn't want certain changes, etc.

**Comment by benhalpern** [comment]
This is great, will get to it soon.

**Comment by StriderHND** [comment]
> Great update, this looks so much better on iPad!
> 
> For future reference, and this applies to any project, it's best to keep unrelated changes as separate PRs just in case something doesn't work, a maintainer doesn't want certain changes, etc.

Sure I'll keep that in mind, thanks! @chickdan

**Comment by StriderHND** [comment]
@benhalpern let me check this one right now.

**Comment by StriderHND** [comment]
@benhalpern changes are made as requested all looks good across all iOS devices. please check.

**Pull request merged**
