### PR TITLE
Double click notifications tab should refresh #12

### PR DESCRIPTION
**Pull request by JacobBoyd**
I also made some autolayout constraint changes in the storyboard, but kept the UI the same.  The updated constraints will just help the UI scale for different devices.  There are more changes needed that I noticed, but I tried to stay within scope of this issue lol

### CODE REVIEW

**Comment by chickdan** [comment]
Hmm, I have some concerns with this PR.

First off is the name of `RootTabBarViewController`, it's called tab bar view controller but isn't a subclass of `UITabBarViewController`. 

Second, at a cursory glance it looks like almost everything in this class is already being done in `DevWebViewController`.

As a tab view controller, this class should handle the changing of the tabs so that we can move away from the storyboard to a more programmatic approach of handling the view hierarchy. To do this, in my opinion, `RootTabBarViewController` should instantiate an array of `DevWebViewController` along with all of the bindings necessary (the appropriate URL for it's corresponding view). For reference checkout [this](https://medium.com/@satindersingh71/uitabbarcontroller-programmatically-2a3df63607f1) article.

**Comment by JacobBoyd** [comment]
I probably could have named the class better, the thought was for the class to be the root view controller in the tab bar.  I did merge `DevWebViewController`,  and probably should have removed `DevWebViewController`, so all VCs are using WKWebViews and have similar implementations.

I like the idea of creating a `UITabBarViewController` subclass to handle the delegate calls and tab selection.

**Comment by JacobBoyd** [comment]
Closed this on accident

**Comment by wahyusumartha** [comment]
I was expecting `RootTabBarViewController` has an array of `DevWebViewController` but apparently it works pretty much the same functionality like `DevWebViewController`, 

or might be you could add `DevWebViewController.view` inside `RootTabBarViewController` so you can reduce duplicated code there

**Comment by benhalpern** [comment]
Where do we stand on all of this @chickdan @JacobBoyd? Should I merge and then allow further refactorings or should we go in another direction?

**Comment by JacobBoyd** [comment]
Hey @benhalpern I like @chickdan 's solution!   I had a busy week but I have some time later today to make the changes!

**Comment by benhalpern** [comment]
Cool, @JacobBoyd can't wait.

**Pull request closed without merging**
