### PR TITLE
Refactor decidePolicyForNavigationAction

### PR DESCRIPTION
**Pull request by Ceri-anne**
Refactored decidePolicyForNavigationAction function to remove force unwraps and hopefully make intent clearer

### CODE REVIEW

**Comment by Ceri-anne** [comment]
Oops! Hopefully fixed now and tests added

**Comment by nebloc** [comment]
Does this PR also fix issue with mailto link in contacts? (https://github.com/thepracticaldev/DEV-ios/issues/97)

**Comment by benhalpern** [comment]
@nebloc

It does not, I believe. But it's related. I'll give that a look ASAP.

@Ceri-anne I'll merge soon. Travis is giving false failures. Will figure it out tomorrow. If you want to give #97 a look and include the fix in this PR before it gets merged, be my guest. Otherwise we'll get to it after.

**Comment by Ceri-anne** [comment]
I'll add the fix for https://github.com/thepracticaldev/DEV-ios/issues/97 before it gets merged @benhalpern. There's a couple of linting errors to fix too so I'll do those

**Comment by Ceri-anne** [comment]
Yep! Good thinking 😊

**Comment by benhalpern** [comment]
Travis is failing but I think it's misconfigured. I'll be merging this later today.

**Comment by nebloc** [comment]
>
> Yep! Good thinking blush Although we’re not switching on the url directly...

@Ceri-anne You are totally right! :grin: What about this? 
``` Swift
if url.scheme == "mailto" {
            openURL(url)
            return .cancel
}

if url.absoluteString == "about:blank" {
            return .allow
} 

if isAuthLink(url) {
            return .allow
} 

if url.host != "dev.to" && navigationType.rawValue == 0 {
            loadInBrowserView(url: url)
            return .cancel
}

return .allow
```

**Comment by Ceri-anne** [comment]
I agree that it’s more readable but it also implies that those if statements can be reordered and it would still work but that’s not true

**Pull request merged**
