### PR TITLE
Won't build in Xcode 10; Home screen has a gap on the right in iPhone XS Max

### PR DESCRIPTION
**Pull request by jacul**
These two commits fixed them by:
Removing the extra script that is causing the error;
Updating the constraints in Storyboard for Home scene.

### CODE REVIEW

**Comment by chickdan** [comment]
Is the error related to using the new build system? Does Xcode 10 now copy the frameworks over without that script?

**Comment by chickdan** [comment]
I just checked it out and the issue isn't with the script. The problem is that the framework is also in the **Embed Frameworks** phase.

**Comment by jacul** [comment]
> I just checked it out and the issue isn't with the script. The problem is that the framework is also in the **Embed Frameworks** phase.

Yes, those two build phases are causing the problem, they conflict. I don't have much experience with Carthage, also since I'm more familiar with the **Embed Frameworks** phase, which is generated by the Xcode, I removed the other script. Correct me if I'm wrong :)

**Comment by chickdan** [comment]
As far as I know Carthage has always required the copy script and their ReadMe still says it's required. I also did some research and found these:

[This](https://github.com/Carthage/Carthage/issues/2598) is an issue in the Carthage repo about the same error. And [here](https://github.com/Carthage/Carthage/issues/1046#issuecomment-173450659) is more info about why _not_ to embed frameworks.

**Comment by jacul** [comment]
> As far as I know Carthage has always required the copy script and their ReadMe still says it's required. I also did some research and found these:
> 
> [This](https://github.com/Carthage/Carthage/issues/2598) is an issue in the Carthage repo about the same error. And [here](https://github.com/Carthage/Carthage/issues/1046#issuecomment-173450659) is more info about why _not_ to embed frameworks.

That makes sense. Should I make a new PR just for the constraints?

**Pull request closed without merging**
