### PR TITLE
Feature/haptic feedback

### PR DESCRIPTION
**Pull request by StriderHND**
This is a PR about the Feature Request #102 that the implementation of Haptic Feedback.

The usage of haptic feedback has been implemented using `WKWebViewConfiguration` and `WKUserContentController` to listen at the events of the webApp doing calls via `webkit.messageHandlers` on the Native side in the `ViewController` class is conforming the `WKScriptMessageHandler ` protocol to get the type of data needed to perform the actions required by the webApp.

for example if we want to have a haptic action in any place of the webApp we have 3 feedback types:

1.  heavy
2. medium
3. light

Execute the haptic we must add the following code in where we want the haptic happens:
```
<script>
 
  function hapticExampleFunction() {

      this is the main implementation the rest of the function can vary.
      window.webkit.messageHandlers.haptic.postMessage("light");
  }
  window.onload = hapticExampleFunction;

</script>
```
we could expand using the `WKScriptMessageHandler` to other webApp -> native communication because we can send JSON objects to the native side via the [WKScriptMessage](https://developer.apple.com/documentation/webkit/wkscriptmessage/1417901-body) that supports basic dataTypes.

If you have questions, let me know 

Erick

### CODE REVIEW

**Comment by benhalpern** [comment]
This looks really great. I'll review it within the next day.

**Comment by benhalpern** [comment]
Hmmmm in my first attempt, I'm getting the `window.webkit.messagehandlers undefined` error.

Seems to bring me here, but that is already in, right?

https://stackoverflow.com/questions/32771215/wkwebkit-javascript-on-loaded-page-finds-window-webkit-is-undefined

May be something more on my end. I'll keep testing. Have you tested it in any way on your machine by loading a local version of dev.to (or a dummy site that just triggers `window.webkit.messageHandlers.haptic.postMessage("light");`)?

**Comment by StriderHND** [comment]
Let me check that pretty fast because the handler lister is there. @benhalpern

**Comment by StriderHND** [comment]
@benhalpern I've made some changes from how the configuration for the webView is set. can you try again please.

**Pull request merged**
